---
default_language_version:
  python: python3

repos:
  - hooks:
      - args:
          - "--safe"
        id: black
        language_version: python3.7
    repo: "https://github.com/ambv/black"
    rev: 18.9b0

  - hooks:
      - additional_dependencies:
          - black==18.9b0
        id: blacken-docs
        language_version: python3.7
    repo: "https://github.com/asottile/blacken-docs"
    rev: v0.3.0

  - hooks:
      - id: isort
        args:
          - --settings-path .
    repo: https://github.com/pycqa/isort
    rev: 5.6.0

  - hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - additional_dependencies:
          - "flake8-bugbear == 18.2.0"
        id: flake8
        language_version: python3.7
    repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v2.4.0
