
[default]
glow_pin = 10 # GPIO pin connected to the pixels (10 uses SPI /dev/spidev0.0).
glow_freq_hz = 800000 # LED signal frequency in hertz (usually 800khz)
glow_dma = 10 # DMA channel to use for generating signal (try 10)
glow_brightness = 255 # Set to 0 for darkest and 255 for brightest
glow_invert = false # True to invert the signal (when using NPN transistor level shift)
glow_channel = 0 # set to '1' for GPIOs 13, 19, 41, 45 or 53

[glow]
strips = [
  { name = "box1", title = "Coffre du haut", size = 74 }
]
